import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import {
  UserButton,
  useUser,
  SignInButton,
  SignOutButton,
} from "@clerk/nextjs";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from Skinwalker Styles" });
  const { user, isSignedIn } = useUser();
  console.log("user", user);
  const { data } = api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <header className="flex w-full max-w-6xl items-center justify-between p-10">
          <div className="text-white">Logo</div>
          <div>
            {isSignedIn ? (
              <div>
                <UserButton afterSignOutUrl="/" />

                <SignOutButton />
              </div>
            ) : (
              <div className="text-white">
                <SignInButton afterSignInUrl="/" />
              </div>
            )}
          </div>
        </header>
        <div>
          {data?.map((post) => {
            return <h3 key={post.id}>{post.content}</h3>;
          })}
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
